// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4BnFtrlzQEQCdoRNoYsHjvcJMa3hKqc0',
    appId: '1:314719046066:web:fbedeacc9488877949fcab',
    messagingSenderId: '314719046066',
    projectId: 'equation-balancer-net',
    authDomain: 'equation-balancer-net.firebaseapp.com',
    storageBucket: 'equation-balancer-net.appspot.com',
    measurementId: 'G-59JZK2SW4T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGNPkwGgrzAap0yPsv9KpH3McgXnFHRD8',
    appId: '1:314719046066:android:285666ddc45e5bc149fcab',
    messagingSenderId: '314719046066',
    projectId: 'equation-balancer-net',
    storageBucket: 'equation-balancer-net.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDw0WWld7TIMfcEUxHhzk--kK28J6CIHio',
    appId: '1:314719046066:ios:e892cd429dc60f7649fcab',
    messagingSenderId: '314719046066',
    projectId: 'equation-balancer-net',
    storageBucket: 'equation-balancer-net.appspot.com',
    iosBundleId: 'com.example.equationbalancer2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDw0WWld7TIMfcEUxHhzk--kK28J6CIHio',
    appId: '1:314719046066:ios:185588a0b9a3d12a49fcab',
    messagingSenderId: '314719046066',
    projectId: 'equation-balancer-net',
    storageBucket: 'equation-balancer-net.appspot.com',
    iosBundleId: 'com.example.equationbalancer2.RunnerTests',
  );
}
